-- CartoonStream Supabase setup
-- Run this in Supabase Dashboard -> SQL Editor before using the admin uploader.

create table if not exists public.cartoons (
  id bigint generated by default as identity primary key,
  title text not null,
  description text default '',
  image_url text default '',
  rating numeric default 8.5,
  year integer default extract(year from now())::integer,
  created_at timestamptz default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  cartoon_id bigint not null references public.cartoons(id) on delete cascade,
  name text not null,
  "order" integer default 0,
  created_at timestamptz default now()
);

create table if not exists public.episodes (
  id bigint generated by default as identity primary key,
  cartoon_id bigint not null references public.cartoons(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  episode_number integer default 1,
  name text not null,
  description text default '',
  duration integer default 1320,
  video_url text not null,
  thumbnail_url text default '',
  views integer default 0,
  audio_languages text[] default array['English', 'Tamil', 'Hindi'],
  created_at timestamptz default now()
);

create index if not exists cartoons_title_idx on public.cartoons(title);
create index if not exists categories_cartoon_idx on public.categories(cartoon_id);
create index if not exists episodes_cartoon_idx on public.episodes(cartoon_id);
create index if not exists episodes_category_idx on public.episodes(category_id);

alter table public.cartoons enable row level security;
alter table public.categories enable row level security;
alter table public.episodes enable row level security;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'cartoons' and policyname = 'Public can read cartoons') then
    create policy "Public can read cartoons" on public.cartoons for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'cartoons' and policyname = 'Authenticated admins can write cartoons') then
    create policy "Authenticated admins can write cartoons" on public.cartoons for all to authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'categories' and policyname = 'Public can read categories') then
    create policy "Public can read categories" on public.categories for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'categories' and policyname = 'Authenticated admins can write categories') then
    create policy "Authenticated admins can write categories" on public.categories for all to authenticated using (true) with check (true);
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'episodes' and policyname = 'Public can read episodes') then
    create policy "Public can read episodes" on public.episodes for select using (true);
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'public' and tablename = 'episodes' and policyname = 'Authenticated admins can write episodes') then
    create policy "Authenticated admins can write episodes" on public.episodes for all to authenticated using (true) with check (true);
  end if;
end $$;

insert into storage.buckets (id, name, public)
values ('cartoon-assets', 'cartoon-assets', true)
on conflict (id) do update set public = true;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public can read cartoon assets') then
    create policy "Public can read cartoon assets" on storage.objects for select using (bucket_id = 'cartoon-assets');
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Authenticated admins can upload cartoon assets') then
    create policy "Authenticated admins can upload cartoon assets" on storage.objects for insert to authenticated with check (bucket_id = 'cartoon-assets');
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Authenticated admins can update cartoon assets') then
    create policy "Authenticated admins can update cartoon assets" on storage.objects for update to authenticated using (bucket_id = 'cartoon-assets') with check (bucket_id = 'cartoon-assets');
  end if;
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Authenticated admins can delete cartoon assets') then
    create policy "Authenticated admins can delete cartoon assets" on storage.objects for delete to authenticated using (bucket_id = 'cartoon-assets');
  end if;
end $$;
